run:
  concurrency: 16
  timeout: 5m
  tests: false
  allow-parallel-runners: true

linters:
  disable:
    - gochecknoglobals
    - varnamelen
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  fast: false
