// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sentinel/plan/v3/plan.proto

package v3

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	v1 "github.com/sentinel-official/hub/v12/types/v1"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Plan struct {
	ID          uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProvAddress string     `protobuf:"bytes,2,opt,name=prov_address,json=provAddress,proto3" json:"prov_address,omitempty"`
	Gigabytes   int64      `protobuf:"varint,3,opt,name=gigabytes,proto3" json:"gigabytes,omitempty"`
	Hours       int64      `protobuf:"varint,4,opt,name=hours,proto3" json:"hours,omitempty"`
	Prices      []v1.Price `protobuf:"bytes,5,rep,name=prices,proto3" json:"prices"`
	Private     bool       `protobuf:"varint,6,opt,name=private,proto3" json:"private,omitempty"`
	Status      v1.Status  `protobuf:"varint,7,opt,name=status,proto3,enum=sentinel.types.v1.Status" json:"status,omitempty"`
	StatusAt    time.Time  `protobuf:"bytes,8,opt,name=status_at,json=statusAt,proto3,stdtime" json:"status_at"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_802b50fd151489fc, []int{0}
}
func (m *Plan) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(m, src)
}
func (m *Plan) XXX_Size() int {
	return m.Size()
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Plan)(nil), "sentinel.plan.v3.Plan")
}

func init() { proto.RegisterFile("sentinel/plan/v3/plan.proto", fileDescriptor_802b50fd151489fc) }

var fileDescriptor_802b50fd151489fc = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x31, 0x8f, 0xd3, 0x30,
	0x18, 0x8d, 0xd3, 0x5e, 0xae, 0x75, 0x11, 0x42, 0xd6, 0x09, 0x99, 0x02, 0x6e, 0x60, 0xca, 0x82,
	0xad, 0xb6, 0x88, 0xbd, 0x15, 0x0b, 0xdb, 0x29, 0x20, 0x06, 0x96, 0x93, 0xd3, 0xba, 0xa9, 0xa5,
	0x34, 0x8e, 0x62, 0x27, 0xe2, 0xfe, 0xc5, 0xfd, 0x0c, 0xfe, 0x04, 0x7b, 0xc7, 0x1b, 0x99, 0x0e,
	0x48, 0xff, 0x08, 0x8a, 0x9d, 0x94, 0x01, 0x26, 0x7f, 0xdf, 0x7b, 0xcf, 0xfe, 0x9e, 0x9f, 0x0d,
	0x9f, 0x6b, 0x91, 0x1b, 0x99, 0x8b, 0x8c, 0x15, 0x19, 0xcf, 0x59, 0xbd, 0xb4, 0x2b, 0x2d, 0x4a,
	0x65, 0x14, 0x7a, 0xd2, 0x93, 0xd4, 0x82, 0xf5, 0x72, 0x7a, 0x95, 0xaa, 0x54, 0x59, 0x92, 0xb5,
	0x95, 0xd3, 0x4d, 0x67, 0xa9, 0x52, 0x69, 0x26, 0x98, 0xed, 0x92, 0x6a, 0xc7, 0x8c, 0x3c, 0x08,
	0x6d, 0xf8, 0xa1, 0xe8, 0x04, 0x2f, 0xcf, 0x53, 0xcc, 0x6d, 0x21, 0x34, 0xab, 0xe7, 0xac, 0x28,
	0xe5, 0x46, 0x74, 0x34, 0xf9, 0x97, 0xd6, 0x86, 0x9b, 0x4a, 0x3b, 0xfe, 0xf5, 0x77, 0x1f, 0x0e,
	0xaf, 0x33, 0x9e, 0xa3, 0xa7, 0xd0, 0x97, 0x5b, 0x0c, 0x42, 0x10, 0x0d, 0xd7, 0x41, 0xf3, 0x30,
	0xf3, 0x3f, 0xbc, 0x8f, 0x7d, 0xb9, 0x45, 0xaf, 0xe0, 0xa3, 0xa2, 0x54, 0xf5, 0x0d, 0xdf, 0x6e,
	0x4b, 0xa1, 0x35, 0xf6, 0x43, 0x10, 0x8d, 0xe3, 0x49, 0x8b, 0xad, 0x1c, 0x84, 0x5e, 0xc0, 0x71,
	0x2a, 0x53, 0x9e, 0xdc, 0x1a, 0xa1, 0xf1, 0x20, 0x04, 0xd1, 0x20, 0xfe, 0x0b, 0xa0, 0x2b, 0x78,
	0xb1, 0x57, 0x55, 0xa9, 0xf1, 0xd0, 0x32, 0xae, 0x41, 0xef, 0x60, 0x60, 0x6d, 0x6a, 0x7c, 0x11,
	0x0e, 0xa2, 0xc9, 0x02, 0xd3, 0x73, 0x20, 0xd6, 0x28, 0xad, 0xe7, 0xf4, 0xba, 0x15, 0xac, 0x87,
	0xc7, 0x87, 0x99, 0x17, 0x77, 0x6a, 0x84, 0xe1, 0x65, 0x51, 0xca, 0x9a, 0x1b, 0x81, 0x83, 0x10,
	0x44, 0xa3, 0xb8, 0x6f, 0xd1, 0x1c, 0x06, 0xee, 0x66, 0xf8, 0x32, 0x04, 0xd1, 0xe3, 0xc5, 0xb3,
	0xff, 0x9c, 0xf8, 0xd1, 0x0a, 0xe2, 0x4e, 0x88, 0x56, 0x70, 0xec, 0xaa, 0x1b, 0x6e, 0xf0, 0x28,
	0x04, 0xd1, 0x64, 0x31, 0xa5, 0x2e, 0x70, 0xda, 0x07, 0x4e, 0x3f, 0xf5, 0x81, 0xaf, 0x47, 0xad,
	0x93, 0xbb, 0x9f, 0x33, 0x10, 0x8f, 0xdc, 0xb6, 0x95, 0x59, 0x7f, 0x3e, 0xfe, 0x26, 0xde, 0xb7,
	0x86, 0x78, 0xc7, 0x86, 0x80, 0xfb, 0x86, 0x80, 0x5f, 0x0d, 0x01, 0x77, 0x27, 0xe2, 0xdd, 0x9f,
	0x88, 0xf7, 0xe3, 0x44, 0xbc, 0x2f, 0x6f, 0x53, 0x69, 0xf6, 0x55, 0x42, 0x37, 0xea, 0xc0, 0x7a,
	0x47, 0x6f, 0xd4, 0x6e, 0x27, 0x37, 0x92, 0x67, 0x6c, 0x5f, 0x25, 0xac, 0x9e, 0x2f, 0xd8, 0x57,
	0xf7, 0x49, 0xba, 0x47, 0x5a, 0x26, 0x81, 0x9d, 0xbf, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x6d,
	0xb6, 0xad, 0x2d, 0x45, 0x02, 0x00, 0x00,
}

func (m *Plan) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Plan) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Plan) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.StatusAt, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StatusAt):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintPlan(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x42
	if m.Status != 0 {
		i = encodeVarintPlan(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x38
	}
	if m.Private {
		i--
		if m.Private {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if len(m.Prices) > 0 {
		for iNdEx := len(m.Prices) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Prices[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPlan(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Hours != 0 {
		i = encodeVarintPlan(dAtA, i, uint64(m.Hours))
		i--
		dAtA[i] = 0x20
	}
	if m.Gigabytes != 0 {
		i = encodeVarintPlan(dAtA, i, uint64(m.Gigabytes))
		i--
		dAtA[i] = 0x18
	}
	if len(m.ProvAddress) > 0 {
		i -= len(m.ProvAddress)
		copy(dAtA[i:], m.ProvAddress)
		i = encodeVarintPlan(dAtA, i, uint64(len(m.ProvAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.ID != 0 {
		i = encodeVarintPlan(dAtA, i, uint64(m.ID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintPlan(dAtA []byte, offset int, v uint64) int {
	offset -= sovPlan(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Plan) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ID != 0 {
		n += 1 + sovPlan(uint64(m.ID))
	}
	l = len(m.ProvAddress)
	if l > 0 {
		n += 1 + l + sovPlan(uint64(l))
	}
	if m.Gigabytes != 0 {
		n += 1 + sovPlan(uint64(m.Gigabytes))
	}
	if m.Hours != 0 {
		n += 1 + sovPlan(uint64(m.Hours))
	}
	if len(m.Prices) > 0 {
		for _, e := range m.Prices {
			l = e.Size()
			n += 1 + l + sovPlan(uint64(l))
		}
	}
	if m.Private {
		n += 2
	}
	if m.Status != 0 {
		n += 1 + sovPlan(uint64(m.Status))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.StatusAt)
	n += 1 + l + sovPlan(uint64(l))
	return n
}

func sovPlan(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPlan(x uint64) (n int) {
	return sovPlan(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Plan) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPlan
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Plan: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Plan: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			m.ID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProvAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPlan
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProvAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gigabytes", wireType)
			}
			m.Gigabytes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Gigabytes |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hours", wireType)
			}
			m.Hours = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Hours |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Prices", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPlan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Prices = append(m.Prices, v1.Price{})
			if err := m.Prices[len(m.Prices)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Private", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Private = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= v1.Status(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPlan
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPlan
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.StatusAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPlan(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPlan
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPlan(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPlan
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPlan
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPlan
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPlan
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPlan
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPlan        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPlan          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPlan = fmt.Errorf("proto: unexpected end of group")
)
