name: Tests and Code Coverage

on:
  pull_request:
  push:
    branches:
      - development
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Generate Coverage Report
        run: |
          make test-coverage
          filepaths=""
          filepaths+=" $(find ./ -type f -name '*.go' -exec grep -l 'DO NOT COVER' {} \;)"
          filepaths+=" $(find ./ -type f -name '*.pb.go')"
          filepaths+=" $(find ./ -type f -name '*.pb.gw.go')"
          filepaths+=" $(find ./ -type f -path '*/client/cli/*')"
          filepaths+=" $(find ./ -type f -path '*/expected/*')"
          filepaths+=" $(find ./ -type f -path '*/services/*')"
          for filepath in ${filepaths}; do
            filepath=$(echo "${filepath}" | sed 's@^.@github.com/sentinel-official/hub/v[0-9]*@g')
            echo "Excluding file ${filepath} from coverage report..."
            sed -i "/$(echo "${filepath}" | sed 's@/@\\/@g')/d" ./coverage.txt
          done

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
